import time
import webbrowser

webbrowser.open('https://www.google.com/')
time.sleep(0.5)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=126512')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=127818')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=129428')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=129615')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=130852')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=130969')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=131672')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=134512')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=134635')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=134945')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=134960')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=135139')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=131241')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=133080')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=136925')
time.sleep(0.1)
webbrowser.open('http://bugz.mvista.com/show_bug.cgi?id=136285')
time.sleep(0.1)
